- Ouster:
  name: /os_node/imu
  hz: 5
- Realsense:
  name: /camera/color/image_raw_throttle/compressed
  hz: 1
- Jackal:
  name: /jackal_velocity_controller/odom
  hz: 1
- Odometry:
  name: /os_node/rofl_odom/pose
  hz: 5
- XView:
  name: /top_down_render/pose_est
  hz: 0
- ASOOM Map:
  name: /titan/asoom/map/compressed
  hz: 0
- Path:
  name: /spomp_global/path_viz
  hz: 0
