- Odometry:
  name: /upslam/global_pose 
  hz: 5
- Map:
  name: /map
  hz: 0.2
- Ouster:
  name: /os1_cloud_node/imu
  hz: 5
- XView:
  name: /upslam/sem_pose
  hz: 5
- ASOOM Map:
  name: /iapetus/asoom/map_sem_img
  hz: 0
- ASOOM Pose:
  name: /iapetus/asoom/recent_key_pose
  hz: 0
- ASOOM Map Center:
  name: /iapetus/asoom/map_sem_img_center
  hz: 0
- Path:
  name: /semantic_planner/path
  hz: 0
